### ISSUE TITLE
Implementar as melhores práticas de CI/CD no repo dotlanche

### ISSUE THREAD

**Issue by atcorrea** [98Lanches/dotlanche#8]
**TO DO:**
Perguntar no grupo se podemos utilizar um teste de exemplo ou precisamos criar testes reais.

Os repositórios devem fazer deploy automatizado na conta da nuvem utilizando actions. As branchs main/master devem ser protegidas, não permitindo commits direto. Sempre utilize pull request

**Comment by ang-costa-neto** [comment]
Fechada, pois ja implementamos as boas praticas na hora da criação
